# Generated by Django 5.2.15 on 2026-06-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='guest', max_length=20)),
                ('full_name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('answer', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to='models.telegramuser')),
                ('to_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_received', to='models.telegramuser')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='models.telegramuser')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
