# Generated by Django 5.2.15 on 2026-06-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('speaker', 'Спикер'), ('organizer', 'Организатор')], default='guest', max_length=20),
        ),
    ]
