# Generated by Django 5.2.15 on 2026-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_telegramuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
