# Generated by Django 5.2.15 on 2026-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_question_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_speaker',
            field=models.BooleanField(default=False),
        ),
    ]
